### ISSUE TITLE
Where can I find the STL file for a plate to mount an Nvidia Jetson Nano?

### ISSUE THREAD

**Issue by ashishk88** [FlorianWilk/SpotMicroAI#7]
Great work on the Spot Micro and thanks for open sourcing your work! I will really appreciate if you could point me to the location of a plate to mount an Nvidia Jetson Nano.

**Comment by ashishk88** [comment]
It will be great if you could also upload the STL for the top cover with holes for LiDAR mounting.

**Comment by jdmueller** [comment]
https://github.com/FlorianWilk/SpotMicroAI/blob/master/STL/top.stl

**Comment by jdmueller** [comment]
https://github.com/FlorianWilk/SpotMicroAI/blob/master/urdf/stl/jetsonPlate.stl

**Comment by ashishk88** [comment]
Thanks a lot!
