### ISSUE TITLE
Electrical Wiring Diagram

### ISSUE THREAD

**Issue by mschwab87** [FlorianWilk/SpotMicroAI#8]
Could you possibly provide a wiring diagram?

**Comment by jimprince** [comment]
what hardware are you looking for a wiring diagram for? For the PCA 9685 to the Jetson Nano or for the servos to the PCA9685? Or something else?

**Comment by mschwab87** [comment]
Hey Brad,

We were able to figure it out. When we started the project we were just
wondering if there was a wiring diagram for the the whole system servos to
pca, pca to jetson etc. Thanks for getting back to me.

Regards,

Matt

**Comment by jimprince** [comment]
No worries. Let me know if you have any other questions.
